/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Dentist model module.
 * @module model/Dentist
 * @version 1.0.0
 */
export class Dentist {
  /**
   * Constructs a new <code>Dentist</code>.
   * @alias module:model/Dentist
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Dentist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dentist} obj Optional instance to populate.
   * @return {module:model/Dentist} The populated <code>Dentist</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Dentist();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('specialty'))
        obj.specialty = ApiClient.convertToType(data['specialty'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Dentist.prototype.id = undefined;

/**
 * @member {String} name
 */
Dentist.prototype.name = undefined;

/**
 * @member {String} specialty
 */
Dentist.prototype.specialty = undefined;

