/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DentistAppointment} from './DentistAppointment';

/**
 * The DentistAppointmentList model module.
 * @module model/DentistAppointmentList
 * @version 1.0.0
 */
export class DentistAppointmentList extends Array {
  /**
   * Constructs a new <code>DentistAppointmentList</code>.
   * @alias module:model/DentistAppointmentList
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DentistAppointmentList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DentistAppointmentList} obj Optional instance to populate.
   * @return {module:model/DentistAppointmentList} The populated <code>DentistAppointmentList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DentistAppointmentList();
      ApiClient.constructFromObject(data, obj, 'DentistAppointment');
    }
    return obj;
  }
}
