/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DentistInput} from './DentistInput';
import {PatientInput} from './PatientInput';

/**
 * The DentistAppointmentInput model module.
 * @module model/DentistAppointmentInput
 * @version 1.0.0
 */
export class DentistAppointmentInput {
  /**
   * Constructs a new <code>DentistAppointmentInput</code>.
   * @alias module:model/DentistAppointmentInput
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DentistAppointmentInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DentistAppointmentInput} obj Optional instance to populate.
   * @return {module:model/DentistAppointmentInput} The populated <code>DentistAppointmentInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DentistAppointmentInput();
      if (data.hasOwnProperty('dentist'))
        obj.dentist = DentistInput.constructFromObject(data['dentist']);
      if (data.hasOwnProperty('patient'))
        obj.patient = PatientInput.constructFromObject(data['patient']);
      if (data.hasOwnProperty('dob'))
        obj.dob = ApiClient.convertToType(data['dob'], 'Date');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/DentistInput} dentist
 */
DentistAppointmentInput.prototype.dentist = undefined;

/**
 * @member {module:model/PatientInput} patient
 */
DentistAppointmentInput.prototype.patient = undefined;

/**
 * @member {Date} dob
 */
DentistAppointmentInput.prototype.dob = undefined;

/**
 * @member {Date} _date
 */
DentistAppointmentInput.prototype._date = undefined;

/**
 * @member {String} time
 */
DentistAppointmentInput.prototype.time = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
DentistAppointmentInput.StatusEnum = {
  /**
   * value: "Scheduled"
   * @const
   */
  scheduled: "Scheduled",

  /**
   * value: "Completed"
   * @const
   */
  completed: "Completed",

  /**
   * value: "Cancele"
   * @const
   */
  cancele: "Cancele",

  /**
   * value: "Pending"
   * @const
   */
  pending: "Pending"
};
/**
 * dentist appointment status
 * @member {module:model/DentistAppointmentInput.StatusEnum} status
 */
DentistAppointmentInput.prototype.status = undefined;

