/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Dentist} from './Dentist';
import {Patient} from './Patient';

/**
 * The DentistAppointment model module.
 * @module model/DentistAppointment
 * @version 1.0.0
 */
export class DentistAppointment {
  /**
   * Constructs a new <code>DentistAppointment</code>.
   * @alias module:model/DentistAppointment
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DentistAppointment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DentistAppointment} obj Optional instance to populate.
   * @return {module:model/DentistAppointment} The populated <code>DentistAppointment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DentistAppointment();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('dentist'))
        obj.dentist = Dentist.constructFromObject(data['dentist']);
      if (data.hasOwnProperty('patient'))
        obj.patient = Patient.constructFromObject(data['patient']);
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
DentistAppointment.prototype.id = undefined;

/**
 * @member {module:model/Dentist} dentist
 */
DentistAppointment.prototype.dentist = undefined;

/**
 * @member {module:model/Patient} patient
 */
DentistAppointment.prototype.patient = undefined;

/**
 * @member {Date} _date
 */
DentistAppointment.prototype._date = undefined;

/**
 * @member {String} time
 */
DentistAppointment.prototype.time = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
DentistAppointment.StatusEnum = {
  /**
   * value: "Scheduled"
   * @const
   */
  scheduled: "Scheduled",

  /**
   * value: "Completed"
   * @const
   */
  completed: "Completed",

  /**
   * value: "Canceled"
   * @const
   */
  canceled: "Canceled",

  /**
   * value: "Pending"
   * @const
   */
  pending: "Pending"
};
/**
 * dentist appointment status
 * @member {module:model/DentistAppointment.StatusEnum} status
 */
DentistAppointment.prototype.status = undefined;

