/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PatientInput model module.
 * @module model/PatientInput
 * @version 1.0.0
 */
export class PatientInput {
  /**
   * Constructs a new <code>PatientInput</code>.
   * @alias module:model/PatientInput
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PatientInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PatientInput} obj Optional instance to populate.
   * @return {module:model/PatientInput} The populated <code>PatientInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PatientInput();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('dob'))
        obj.dob = ApiClient.convertToType(data['dob'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PatientInput.prototype.name = undefined;

/**
 * @member {Date} dob
 */
PatientInput.prototype.dob = undefined;

