/*
 * Dentist Appointment API
 * API for managing Dentist Appointment
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DentistAppointmentApi);
  }
}(this, function(expect, DentistAppointmentApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Dentist', function() {
      beforeEach(function() {
        instance = new DentistAppointmentApi.Dentist();
      });

      it('should create an instance of Dentist', function() {
        // TODO: update the code to test Dentist
        expect(instance).to.be.a(DentistAppointmentApi.Dentist);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property specialty (base name: "specialty")', function() {
        // TODO: update the code to test the property specialty
        expect(instance).to.have.property('specialty');
        // expect(instance.specialty).to.be(expectedValueLiteral);
      });

    });
  });

}));
